name: PHPunit
on: push

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer install
        uses: php-actions/composer@v5

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --testdox
